project_name: "jelliflix"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      386: i386
      linux: Linux
      amd64: x86_64
      darwin: Darwin
      windows: Windows

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
