---
name: Publish
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  lint:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Set Environment Variables
        run: |
          IMG=jelliflix
          echo "::set-env name=IMG::${IMG}"
          echo "::set-env name=BUILD_VER::1.0.$GITHUB_RUN_NUMBER"
          echo "::set-env name=IMAGE::ghcr.io/${{ github.repository_owner }}/${IMG}"
          echo "::set-env name=GIT_SHA::$(echo ${{ github.sha }} | cut -c1-7)"
          echo "::set-env name=GIT_REF::$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)"
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.GIT_REF }}
            ${{ env.IMAGE }}:${{ env.GIT_SHA }}
            ${{ env.IMAGE }}:${{ env.BUILD_VER }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
