---
name: Publish
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  lint:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/jelliflix/jelliflix:latest
          docker run ghcr.io/jelliflix/jelliflix:latest
          docker push ghcr.io/jelliflix/jelliflix:latest
